version: "3.9"

services:
  backend:
    build: .
    container_name: sigiv-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sigiv
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: always

  mysql:
    image: mysql:8.0
    container_name: sigiv-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sigiv
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
